language: node_js
dist: bionic
node_js:
  - "12"

services:
  - xvfb

env:
  global:
    - SAUCE_USERNAME=pkozlowski
    - SAUCE_ACCESS_KEY=c5ea8b730bc9-378b-43e4-6e34-e66aa371
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs
    - PLAYWRIGHT_BROWSERS_PATH=0

addons:
  chrome: stable
  apt:
    packages:
    # These are required to run webkit
    - libwoff1
    - libopus0
    - libwebp6
    - libwebpdemux2
    - libenchant1c2a
    - libgudev-1.0-0
    - libsecret-1-0
    - libhyphen0
    - libgdk-pixbuf2.0-0
    - libegl1
    - libgles2
    - libevent-2.1-6
    - libnotify4
    - libxslt1.1
    - libvpx5

    # gstreamer and plugins to support video playback in WebKit.
    - gstreamer1.0-gl
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad

install:
  - yarn install --frozen-lockfile

cache: yarn

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"

before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh

script:
  - yarn ci && yarn scripts:test
  - yarn global add codecov && codecov --disable=gcov -f coverage/lcov.info -F unit && codecov --disable=gcov -f coverage-e2e/lcov.info -F e2e
  - ./scripts/sauce_connect_block.sh
  - yarn saucelabs
  - yarn saucelabs:ie

after_script:
  - ./scripts/sauce_connect_teardown.sh

sudo: false
